name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: UT for BtsApplication
      run: make BtsApplicationUT 
    - name: UT for BTS_Tests
      run: make BTS_Tests 
    - name: UT for COMMON
      run: make COMMON_UT
    - name: UT for UeApplication
      run: make UeApplicationUT
    - name: UT for UE_Tests
      run: make UE_Tests
    - name: next steps
      run: echo "karamba"
    
